[package]
name = "postgrs"
version = "0.1.0"
authors = ["Damien Szczyt <dszczyt@work4labs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cached = "0.12"
crc = "^1.0.0"
memoffset = "^0.5"